countries=c("INDIA","CHINA","JAPAN","ROMANIA","INDONESIA","CANADA","NETHERLANDS","AUSTRALIA","HUNGARY","RUSSIA")
if(is.element("MEXICO",countries)){
  cat("COUNTRY IS PRESENT IN THE VECTOR")
}else{
  cat("COUNTRY IS NOT PRESENT IN THE VECTOR")
}
